before_script:
  - cp .env.example .env
  - yarn install

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy
  - analysis

jest:
  stage: test
  script:
    - yarn coverage
  artifacts:
    paths:
      - coverage
  when: on_success

sonar:
  stage: analysis
  dependencies:
    - jest
  script:
    - sonar-scanner -Dsonar.projectKey=style-guide -Dsonar.sources=$PWD -Dsonar.exclusions=**/node_modules/**,dist/**/* -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
  tags:
    - style

storybook:
  stage: build
  script:
    - yarn build-storybook
  artifacts:
    paths:
      - storybook-static
  tags:
    - style
  only:
    - master

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r storybook-static/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - style

after_script:
  - yarn cache clean
