before_script:
  - cp .env.example .env
  - yarn install

cache:
  paths:
  - node_modules/

storybook:
  stage: build
  script:
    - yarn build-storybook
    - ls -la
  artifacts:
    paths:
      - storybook-static
    expire_in: 1 hour
  tags:
    - style

jest:
  stage: test
  script:
    - yarn coverage
  tags:
    - style

eslint:
  stage: test
  script:
    - yarn lint
  tags:
    - style

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r storybook-static/* .public
    - mv .public public
  artifacts:
    paths:
      - public
